### ISSUE TITLE
build error undefined: blackfriday.EXTENSION_DEFINITION_LISTS

### ISSUE THREAD

**Issue by edrex** [mholt/caddy#583]
Introduced in 3278106421a6cd8721117525184f77bf8b602111

**Comment by mholt** [comment]
That's weird, it passed CI tests. Try `go get -u github.com/russross/blackfriday` then build again, let me know.

**Comment by edrex** [comment]
Hmm, yes it worked after that. Maybe I had an old version of blackfriday?
